version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - run:
          name: 最初の一歩
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: コードの取得
          command: |
            ls -la
            echo '^^^That should look familiar^^^'

