version: 2.1

executors:
  test:
    docker:
      - image: circleci/ruby:2.6.6-buster-node
        environment:
          RAILS_ENV: "test"
          DB_USERNAME: "root"
          DB_PASSWORD: ""
          DB_SERVERNAME: "127.0.0.1"
          TZ: "Asia/Tokyo"
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_HOST: "127.0.0.1"
          MYSQL_USER: "root"

commands:
  install_gem_dependencies:
    steps:
      - restore_cache:
          name: Restore gem dependencies
          key: v1-circleci-training-gem-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: BUNDLE_GEMFILE=Gemfile bundle install --path vendor/bundle --jobs=4
      - save_cache:
          key: v1-circleci-training-gem-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  front_setup:
    steps:
      - restore_cache:
          name: Restore node_modules dependencies
          key: v1-circleci-training-node-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-circleci-training-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: webpacker compile
          command: bundle exec rails webpacker:compile
  db_setup:
    steps:
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m -wait-retry-interval 5s
      - run:
          name: db setup
          command: bundle exec rails db:setup
  exec_spec:
    steps:
      - run: mkdir ~/rspec
      - run:
          name: Run tests
          command: |
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/rspec

workflows:
  test:
    jobs:
      - backend-test

jobs:
  backend-test:
    executor: test
    steps:
      - checkout
      - install_gem_dependencies
      - front_setup
      - db_setup
      - exec_spec
